import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import type { RootState } from '../store/index.ts';
import { addMessage } from '../store/chatSlice.ts';
import { Send, Sparkles, MoreVertical, Phone, Video, Paperclip, Smile } from 'lucide-react';

interface ChatAreaProps {
  convId: string;
}

const ChatArea: React.FC<ChatAreaProps> = ({ convId }) => {
  const dispatch = useDispatch();
  const { user } = useSelector((state: RootState) => state.auth);
  const { conversations, messages } = useSelector((state: RootState) => state.chat);
  
  const [inputText, setInputText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const conv = conversations.find(c => c._id === convId);
  const convMessages = useMemo(() => messages[convId] || [], [messages, convId]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [convMessages, convId]);

  if (!conv) return null;

  const participantName = conv.isGroup ? null : conv.participants.find(p => p._id !== user?._id)?.name;
  const displayTitle = conv.title || participantName || 'Unknown User';

  const handleSendMessage = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!inputText.trim()) return;

    dispatch(addMessage({
      _id: `m_${Date.now()}`,
      conversationId: convId,
      senderId: user!._id,
      content: inputText,
      isRead: false,
      createdAt: new Date().toISOString(),
    }));
    setInputText('');
  };

  const handleSmartReply = (text: string) => {
    setInputText(text);
  };

  // Mock smart replies generated by "Gemini"
  const smartReplies = [
    "Sounds good to me!",
    "I'll check it and get back to you.",
    "Can we discuss this on a call?"
  ];

  return (
    <>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem 1.5rem', borderBottom: '1px solid var(--border-medium)', background: 'rgba(255,255,255,0.02)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{ width: '40px', height: '40px', borderRadius: 'var(--radius-full)', background: 'var(--bg-tertiary)', overflow: 'hidden' }}>
            <img src={`https://ui-avatars.com/api/?name=${displayTitle}`} alt="Avatar" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
          </div>
          <div>
            <h3 style={{ margin: 0, fontSize: '1.1rem' }}>{displayTitle}</h3>
            <span style={{ fontSize: '0.8rem', color: 'var(--success)' }}>
               {isTyping ? 'Typing...' : 'Online'}
            </span>
          </div>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button className="btn-icon"><Phone size={20} /></button>
          <button className="btn-icon"><Video size={20} /></button>
          <button className="btn-icon"><MoreVertical size={20} /></button>
        </div>
      </div>

      {/* Messages */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        <div style={{ textAlign: 'center', margin: '1rem 0' }}>
          <span style={{ background: 'var(--bg-tertiary)', padding: '0.25rem 0.75rem', borderRadius: 'var(--radius-full)', fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>
            Today
          </span>
        </div>

        {convMessages.map((msg) => {
          const isMine = msg.senderId === user?._id;
          const sender = isMine ? user : conv.participants.find(p => p._id === msg.senderId);

          return (
            <div key={msg._id} style={{ display: 'flex', gap: '0.75rem', alignSelf: isMine ? 'flex-end' : 'flex-start', maxWidth: '75%', flexDirection: isMine ? 'row-reverse' : 'row' }}>
              {!isMine && (
                <div style={{ width: '32px', height: '32px', borderRadius: 'var(--radius-full)', overflow: 'hidden', flexShrink: 0 }}>
                  <img src={`https://ui-avatars.com/api/?name=${sender?.name || 'U'}`} alt="avatar" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
              )}
              
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: isMine ? 'flex-end' : 'flex-start' }}>
                {!isMine && conv.isGroup && (
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)', marginBottom: '0.25rem', marginLeft: '0.5rem' }}>
                    {sender?.name}
                  </span>
                )}
                
                <div style={{ 
                  background: isMine ? 'var(--accent-gradient)' : 'var(--bg-tertiary)',
                  color: isMine ? 'white' : 'var(--text-primary)',
                  padding: '0.75rem 1rem',
                  borderRadius: isMine ? '1.5rem 1.5rem 0 1.5rem' : '1.5rem 1.5rem 1.5rem 0',
                  boxShadow: 'var(--shadow-sm)',
                  lineHeight: 1.4
                }}>
                  {msg.content}
                </div>
                
                <span style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', marginTop: '0.25rem' }}>
                  {new Date(msg.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            </div>
          );
        })}
        <div ref={messagesEndRef} />
      </div>

      {/* Gemini Smart Replies Component Area */}
      {convMessages.length > 0 && convMessages[convMessages.length - 1].senderId !== user?._id && (
        <div style={{ padding: '0.5rem 1.5rem', display: 'flex', gap: '0.5rem', overflowX: 'auto', borderTop: '1px solid var(--border-light)', background: 'rgba(99, 102, 241, 0.05)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-secondary)', fontSize: '0.8rem', fontWeight: 600, paddingRight: '0.5rem' }}>
            <Sparkles size={16} /> Gemini
          </div>
          {smartReplies.map((reply, i) => (
            <button 
              key={i}
              onClick={() => handleSmartReply(reply)}
              style={{
                background: 'var(--bg-tertiary)', border: '1px solid var(--border-medium)',
                borderRadius: 'var(--radius-full)', padding: '0.4rem 1rem', fontSize: '0.8rem',
                color: 'var(--text-secondary)', whiteSpace: 'nowrap', transition: 'all var(--transition-fast)'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--accent-primary)'; e.currentTarget.style.color = 'var(--text-primary)' }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border-medium)'; e.currentTarget.style.color = 'var(--text-secondary)' }}
            >
              {reply}
            </button>
          ))}
        </div>
      )}

      {/* Input Area */}
      <div style={{ padding: '1rem 1.5rem', background: 'rgba(255,255,255,0.02)', borderTop: '1px solid var(--border-medium)' }}>
        <form onSubmit={handleSendMessage} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <button type="button" className="btn-icon"><Paperclip size={20} /></button>
          
          <div style={{ flex: 1, position: 'relative' }}>
            <input 
              type="text" 
              className="input-glass" 
              placeholder="Type a message..." 
              value={inputText}
              onChange={(e) => {
                setInputText(e.target.value);
                if (e.target.value.length > 0 && !isTyping) setIsTyping(true);
                else if (e.target.value.length === 0 && isTyping) setIsTyping(false);
              }}
              style={{ borderRadius: 'var(--radius-full)', paddingRight: '3rem' }}
            />
            <button type="button" style={{ position: 'absolute', right: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-tertiary)' }}>
              <Smile size={20} />
            </button>
          </div>
          
          <button 
            type="submit" 
            className="btn-primary" 
            style={{ width: '48px', height: '48px', padding: 0, borderRadius: 'var(--radius-full)' }}
            disabled={!inputText.trim()}
          >
            <Send size={20} style={{ transform: 'translateX(-1px)' }} />
          </button>
        </form>
      </div>
    </>
  );
};

export default ChatArea;
